"""IntelliDesk AI — DTOs package."""

from .auth_dto import (
    AuditLogResponseSchema,
    ChangePasswordSchema,
    CreateDepartmentSchema,
    DepartmentResponseSchema,
    DepartmentSummarySchema,
    ForgotPasswordSchema,
    LoginSchema,
    LogoutSchema,
    RefreshSchema,
    RegisterSchema,
    ResendVerificationSchema,
    ResetPasswordSchema,
    RoleSchema,
    UpdateDepartmentSchema,
    UpdateProfileSchema,
    UpdateUserAdminSchema,
    UserListQuerySchema,
    UserResponseSchema,
    UserSummarySchema,
    VerifyEmailSchema,
)

__all__ = [
    "RegisterSchema",
    "LoginSchema",
    "RefreshSchema",
    "LogoutSchema",
    "ForgotPasswordSchema",
    "ResetPasswordSchema",
    "VerifyEmailSchema",
    "ResendVerificationSchema",
    "ChangePasswordSchema",
    "UserResponseSchema",
    "UserSummarySchema",
    "RoleSchema",
    "DepartmentSummarySchema",
    "UpdateProfileSchema",
    "UpdateUserAdminSchema",
    "UserListQuerySchema",
    "DepartmentResponseSchema",
    "CreateDepartmentSchema",
    "UpdateDepartmentSchema",
    "AuditLogResponseSchema",
]
