"""add is_truncated to ai_messages

Revision ID: 5378095d8bdf
Revises: 1b0956725572
Create Date: 2026-10-09 08:38:38.557299+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5378095d8bdf'
down_revision = '1b0956725572'
branch_labels = None
depends_on = None


def upgrade():
    # server_default='false' backfills existing rows before NOT NULL is enforced.
    # This is required because the table already has data.
    op.add_column('ai_messages', sa.Column(
        'is_truncated', sa.Boolean(), nullable=False, server_default='false'
    ))
    # Remove the server default after backfill — the application always sets this explicitly.
    op.alter_column('ai_messages', 'is_truncated', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_messages', 'is_truncated')
    # ### end Alembic commands ###
