"""add_ticket_created_to_ai_messages

Revision ID: 1b0956725572
Revises: f92881a287c0
Create Date: 2026-08-02 18:28:07.292450+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0956725572'
down_revision = 'f92881a287c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_messages', sa.Column('ticket_created', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_messages', 'ticket_created')
    # ### end Alembic commands ###
